import type { Metadata } from "next";
import ProfileSidebar from "./_components/ProfileSidebar";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function PosterLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <div className=" p-top bg-light-grey md:h-dvh relative">
      <div className="container-w h-full relative overflow-y-auto">
        <div className="w-full md:h-[calc(100%-14px)] flex flex-col md:flex-row gap-y-3 gap-x-5 md:mt-[14px]">
          <ProfileSidebar />
          <div className="paper h-full overflow-y-auto flex-1 rounded-b-none">
            <div className="w-full pb-10">
              <div className="relative w-full">{children}</div>
            </div>
          </div>
        </div>
      </div>
    </div>
  );
}
