export const categoryOptions = [
  {
    id: 1,
    name: "Assembler & Installer",
    slug: "assembler-installer",
    subcategories: [
      { id: 28, name: "Furniture Assembler", slug: "furniture-assembler" },
      { id: 29, name: "Appliance Installer", slug: "appliance-installer" },
      { id: 30, name: "TV Mounting", slug: "tv-mounting" },
    ],
  },
  {
    id: 2,
    name: "Cleaning & Maintenance",
    slug: "cleaning-maintenance",
    subcategories: [
      { id: 31, name: "House Cleaning", slug: "house-cleaning" },
      { id: 32, name: "Carpet Cleaning", slug: "carpet-cleaning" },
      { id: 33, name: "Window Cleaning", slug: "window-cleaning" },
      { id: 34, name: "Gutter Cleaning", slug: "gutter-cleaning" },
      { id: 35, name: "Pressure Washing", slug: "pressure-washing" },
      { id: 36, name: "Pool Cleaning", slug: "pool-cleaning" },
      { id: 37, name: "Lawn Mowing", slug: "lawn-mowing" },
      { id: 38, name: "Gardening", slug: "gardening" },
      { id: 39, name: "Snow Removal", slug: "snow-removal" },
    ],
  },
  {
    id: 3,
    name: "Delivery & Moving",
    slug: "delivery-moving",
    subcategories: [
      { id: 40, name: "Furniture Delivery", slug: "furniture-delivery" },
      { id: 41, name: "Appliance Delivery", slug: "appliance-delivery" },
      { id: 42, name: "General Delivery", slug: "general-delivery" },
      { id: 43, name: "Moving Help", slug: "moving-help" },
      { id: 44, name: "Junk Removal", slug: "junk-removal" },
    ],
  },
  {
    id: 4,
    name: "Handyman Services",
    slug: "handyman-services",
    subcategories: [
      { id: 45, name: "Home Repairs", slug: "home-repairs" },
      { id: 46, name: "Painting", slug: "painting" },
      { id: 47, name: "Drywall Repair", slug: "drywall-repair" },
      { id: 48, name: "Tile Installation", slug: "tile-installation" },
      { id: 49, name: "Flooring Installation", slug: "flooring-installation" },
      { id: 50, name: "Carpentry", slug: "carpentry" },
      { id: 51, name: "Plumbing", slug: "plumbing" },
      { id: 52, name: "Electrical", slug: "electrical" },
      { id: 53, name: "HVAC Services", slug: "hvac-services" },
      { id: 54, name: "Roofing", slug: "roofing" },
      { id: 55, name: "Fencing", slug: "fencing" },
      { id: 56, name: "Deck & Patio", slug: "deck-patio" },
    ],
  },
  {
    id: 5,
    name: "Personal Assistance",
    slug: "personal-assistance",
    subcategories: [
      { id: 57, name: "Errand Running", slug: "errand-running" },
      { id: 58, name: "Personal Shopping", slug: "personal-shopping" },
      { id: 59, name: "Event Assistance", slug: "event-assistance" },
      { id: 60, name: "Virtual Assistance", slug: "virtual-assistance" },
    ],
  },
];
