import { CategoryTab, Tasker } from "./tasker.types";

import {
  Wrench,
  Car,
  Sparkles,
  PartyPopper,
  Truck,
  Calendar,
  Hammer,
  BrushCleaning,
} from "lucide-react";

export const CATEGORY_TABS: CategoryTab[] = [
  {
    id: "assembler",
    name: "Assembler & Installer",
    icon: <Wrench size={18} />,
  },
  { id: "automobile", name: "Automobile", icon: <Car size={18} /> },
  { id: "fashion", name: "Fashion & Beauty", icon: <Sparkles size={18} /> },
  { id: "cleaner", name: "Cleaner", icon: <BrushCleaning size={18} /> },
  { id: "party", name: "Party", icon: <PartyPopper size={18} /> },
  { id: "deliverer", name: "Deliverer", icon: <Truck size={18} /> },
  { id: "event", name: "Event Planner", icon: <Calendar size={18} /> },
  { id: "handyman", name: "Handyman", icon: <Hammer size={18} /> },
];

export const MOCK_TASKERS: Tasker[] = [
  {
    id: "1",
    name: "Samuel Okafor",
    profession: "Licensed Plumbing Technician",
    rating: 4.8,
    reviewCount: 312,
    price: 15000,
    image: "/images/taskers/tasker_2.svg",
    categoryId: "plumbing",
  },
  {
    id: "2",
    name: "Adebayo Ogunleye",
    profession: "Certified Electrical Engineer",
    rating: 4.9,
    reviewCount: 428,
    price: 18000,
    image: "/images/taskers/tasker_4.svg",
    categoryId: "electrical",
  },
  {
    id: "3",
    name: "Blessing Akinwale",
    profession: "Interior Design Consultant",
    rating: 4.7,
    reviewCount: 265,
    price: 25000,
    image: "/images/taskers/tasker_3.svg",
    categoryId: "interior-design",
  },
  {
    id: "4",
    name: "Ibrahim Musa",
    profession: "Custom Furniture Carpenter",
    rating: 4.6,
    reviewCount: 198,
    price: 14000,
    image: "/images/taskers/tasker_4.svg",
    categoryId: "carpentry",
  },
  {
    id: "5",
    name: "Peace Daniels",
    profession: "Residential & Office Cleaning Specialist",
    rating: 4.8,
    reviewCount: 354,
    price: 10000,
    image: "/images/taskers/tasker_2.svg",
    categoryId: "cleaning",
  },
  {
    id: "6",
    name: "Chinedu Nwankwo",
    profession: "Event Planning & Logistics Manager",
    rating: 4.9,
    reviewCount: 417,
    price: 40000,
    image: "/images/taskers/tasker_4.svg",
    categoryId: "event-management",
  },
  {
    id: "7",
    name: "Zainab Bello",
    profession: "Professional Makeup & Beauty Artist",
    rating: 5.0,
    reviewCount: 512,
    price: 20000,
    image: "/images/taskers/tasker_1.svg",
    categoryId: "beauty",
  },
  {
    id: "8",
    name: "Daniel Eze",
    profession: "Logistics & Last-Mile Delivery Specialist",
    rating: 4.6,
    reviewCount: 287,
    price: 7000,
    image: "/images/taskers/tasker_3.svg",
    categoryId: "delivery",
  },
  {
    id: "9",
    name: "Tosin Adeyemi",
    profession: "Air Conditioner Installation & Repair Technician",
    rating: 4.8,
    reviewCount: 339,
    price: 22000,
    image: "/images/taskers/tasker_1.svg",
    categoryId: "hvac",
  },
  {
    id: "10",
    name: "Kelvin Obasi",
    profession: "Automobile Diagnostics & Repair Specialist",
    rating: 4.7,
    reviewCount: 301,
    price: 20000,
    image: "/images/taskers/tasker_2.svg",
    categoryId: "automobile",
  },
  {
    id: "11",
    name: "Funke Alabi",
    profession: "Laundry & Garment Care Professional",
    rating: 4.6,
    reviewCount: 224,
    price: 8000,
    image: "/images/taskers/tasker_3.svg",
    categoryId: "laundry",
  },
  {
    id: "12",
    name: "Sadiq Lawal",
    profession: "Home Painting & Wall Finishing Expert",
    rating: 4.8,
    reviewCount: 276,
    price: 18000,
    image: "/images/taskers/tasker_4.svg",
    categoryId: "painting",
  },
  {
    id: "13",
    name: "Rita Onyekachi",
    profession: "Professional Catering & Meal Prep Specialist",
    rating: 4.9,
    reviewCount: 361,
    price: 30000,
    image: "/images/taskers/tasker_1.svg",
    categoryId: "catering",
  },
  {
    id: "14",
    name: "Yusuf Abdullahi",
    profession: "Smart Home & CCTV Installation Technician",
    rating: 4.7,
    reviewCount: 244,
    price: 25000,
    image: "/images/taskers/tasker_2.svg",
    categoryId: "security-installation",
  },
  {
    id: "15",
    name: "Esther Uche",
    profession: "Childcare & Home Nanny Services",
    rating: 4.9,
    reviewCount: 402,
    price: 12000,
    image: "/images/taskers/tasker_3.svg",
    categoryId: "childcare",
  },
  {
    id: "16",
    name: "Ahmed Sule",
    profession: "Moving & Home Relocation Specialist",
    rating: 4.6,
    reviewCount: 219,
    price: 35000,
    image: "/images/taskers/tasker_4.svg",
    categoryId: "moving",
  },
];
