import { CategoryTab, Tasker } from "./tasker.types";

import {
  Wrench,
  Car,
  Sparkles,
  PartyPopper,
  Truck,
  Calendar,
  Hammer,
  BrushCleaning,
} from "lucide-react";

export const MOCK_TASKERS: Tasker[] = [
  {
    id: "1",
    name: "Shamtel Dickson",
    profession: "Plumbing Engineer",
    rating: 4.6,
    reviewCount: 150,
    price: 10000,
    image: "/images/taskers/tasker_2.svg",
    categoryId: "automobile",
  },
  {
    id: "2",
    name: "John Emmanuel",
    profession: "Electrical Technician",
    rating: 4.8,
    reviewCount: 203,
    price: 12000,
    image: "/images/taskers/tasker_4.svg",
    categoryId: "automobile",
  },
  {
    id: "3",
    name: "Sarah Johnson",
    profession: "Interior Designer",
    rating: 4.9,
    reviewCount: 178,
    price: 15000,
    image: "/images/taskers/tasker_3.svg",
    categoryId: "assembler",
  },
  {
    id: "4",
    name: "Michael Brown",
    profession: "Carpenter",
    rating: 4.7,
    reviewCount: 165,
    price: 11000,
    image: "/images/taskers/tasker_4.svg",
    categoryId: "assembler",
  },
  {
    id: "5",
    name: "Amanda Wilson",
    profession: "Professional Cleaner",
    rating: 4.6,
    reviewCount: 142,
    price: 8000,
    image: "/images/taskers/tasker_2.svg",
    categoryId: "cleaner",
  },
  {
    id: "6",
    name: "David Martinez",
    profession: "Event Coordinator",
    rating: 4.8,
    reviewCount: 189,
    price: 20000,
    image: "/images/taskers/tasker_4.svg",
    categoryId: "event",
  },
  {
    id: "7",
    name: "Lisa Anderson",
    profession: "Makeup Artist",
    rating: 4.9,
    reviewCount: 225,
    price: 13000,
    image: "/images/taskers/tasker_1.svg",
    categoryId: "fashion",
  },
  {
    id: "8",
    name: "Robert Taylor",
    profession: "Delivery Driver",
    rating: 4.5,
    reviewCount: 134,
    price: 5000,
    image: "/images/taskers/tasker_3.svg",
    categoryId: "deliverer",
  },
];

export const CATEGORY_TABS: CategoryTab[] = [
  {
    id: "assembler",
    name: "Assembler & Installer",
    icon: <Wrench size={18} />,
  },
  { id: "automobile", name: "Automobile", icon: <Car size={18} /> },
  { id: "fashion", name: "Fashion & Beauty", icon: <Sparkles size={18} /> },
  { id: "cleaner", name: "Cleaner", icon: <BrushCleaning size={18} /> },
  { id: "party", name: "Party", icon: <PartyPopper size={18} /> },
  { id: "deliverer", name: "Deliverer", icon: <Truck size={18} /> },
  { id: "event", name: "Event Planner", icon: <Calendar size={18} /> },
  { id: "handyman", name: "Handyman", icon: <Hammer size={18} /> },
];
