import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function LegalLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <div className="container-w py-5 sm:py-10 px-4 md:px-16 w-full mt-20">
      {children}
    </div>
  );
}
